# AUTOGENERATED! DO NOT EDIT! File to edit: ../../pts/app.pct.py.

# %% auto 0
__all__ = ['app']

# %% ../../pts/app.pct.py 3
import typer

# %% ../../pts/app.pct.py 4
app = typer.Typer(invoke_without_command=True)
