# AUTOGENERATED! DO NOT EDIT! File to edit: ../../pts/const.pct.py.

# %% auto 0
__all__ = ['snippets_path']

# %% ../../pts/const.pct.py 3
from pathlib import Path
import add_to_pet as proj

# %% ../../pts/const.pct.py 4
snippets_path = Path.home() / ".config/pet/snippet.toml"
