# AUTOGENERATED! DO NOT EDIT! File to edit: ../../pts/utils.pct.py.

# %% auto 0
__all__ = ['foo']

# %% ../../pts/utils.pct.py 3
import add_to_pet as proj
from . import const

# %% ../../pts/utils.pct.py 4
def foo():
    print("Hello")
